# Generated by Django 3.2.21 on 2024-05-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='emp_id',
            new_name='e_id',
        ),
    ]
