# Generated by Django 3.2.21 on 2024-05-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_rename_emp_id_emp_e_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('testimonial', models.TextField()),
                ('pictur', models.ImageField(upload_to='testimonials/')),
                ('rating', models.IntegerField(max_length=1)),
            ],
        ),
    ]
